// //------------------------------------------------------------------------------
// // <auto-generated>
// //     This code was generated by a tool.
// //
// //     Changes to this file may cause incorrect behavior and will be lost if
// //     the code is regenerated.
// // </auto-generated>
// //------------------------------------------------------------------------------
//
// // Generated from: battleEditor.proto
// // Note: requires additional types generated from: common.proto
// namespace proto.battleEditor
// {
//   [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapInfo")]
//   public partial class MapInfo : global::ProtoBuf.IExtensible
//   {
//     public MapInfo() {}
//     
//     private int _mapId;
//     [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mapId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
//     public int MapId
//     {
//       get { return _mapId; }
//       set { _mapId = value; }
//     }
//     private string _mapImage;
//     [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"mapImage", DataFormat = global::ProtoBuf.DataFormat.Default)]
//     public string MapImage
//     {
//       get { return _mapImage; }
//       set { _mapImage = value; }
//     }
//     private string _reward;
//     [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"reward", DataFormat = global::ProtoBuf.DataFormat.Default)]
//     public string Reward
//     {
//       get { return _reward; }
//       set { _reward = value; }
//     }
//     private readonly global::System.Collections.Generic.List<proto.battleEditor.Round> _roundInfo = new global::System.Collections.Generic.List<proto.battleEditor.Round>();
//     [global::ProtoBuf.ProtoMember(4, Name=@"roundInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
//     public global::System.Collections.Generic.List<proto.battleEditor.Round> roundInfo
//     {
//       get { return _roundInfo; }
//     }
//   
//     private global::ProtoBuf.IExtension extensionObject;
//     global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
//       { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
//   }
//   
//   [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Round")]
//   public partial class Round : global::ProtoBuf.IExtensible
//   {
//     public Round() {}
//     
//     private float _roundTime;
//     [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roundTime", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
//     public float RoundTime
//     {
//       get { return _roundTime; }
//       set { _roundTime = value; }
//     }
//     private readonly global::System.Collections.Generic.List<proto.battleEditor.TimeLine> _timeline = new global::System.Collections.Generic.List<proto.battleEditor.TimeLine>();
//     [global::ProtoBuf.ProtoMember(2, Name=@"timeline", DataFormat = global::ProtoBuf.DataFormat.Default)]
//     public global::System.Collections.Generic.List<proto.battleEditor.TimeLine> timeline
//     {
//       get { return _timeline; }
//     }
//   
//     private global::ProtoBuf.IExtension extensionObject;
//     global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
//       { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
//   }
//   
//   [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TimeLine")]
//   public partial class TimeLine : global::ProtoBuf.IExtensible
//   {
//     public TimeLine() {}
//     
//     private float _time;
//     [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
//     public float time
//     {
//       get { return _time; }
//       set { _time = value; }
//     }
//     private readonly global::System.Collections.Generic.List<int> _enemys = new global::System.Collections.Generic.List<int>();
//     [global::ProtoBuf.ProtoMember(2, Name=@"enemys", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
//     public global::System.Collections.Generic.List<int> enemys
//     {
//       get { return _enemys; }
//     }
//   
//     private global::ProtoBuf.IExtension extensionObject;
//     global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
//       { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
//   }
//   
//   [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapObject")]
//   public partial class MapObject : global::ProtoBuf.IExtensible
//   {
//     public MapObject() {}
//     
//     private proto.battleEditor.MapObjectType _type;
//     [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
//     public proto.battleEditor.MapObjectType Type
//     {
//       get { return _type; }
//       set { _type = value; }
//     }
//     private int _id;
//     [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
//     public int Id
//     {
//       get { return _id; }
//       set { _id = value; }
//     }
//     private float _rotateDegree;
//     [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"rotateDegree", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
//     public float RotateDegree
//     {
//       get { return _rotateDegree; }
//       set { _rotateDegree = value; }
//     }
//     private global::ProtoBuf.IExtension extensionObject;
//     global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
//       { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
//   }
//   
//   [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MachineObject")]
//   public partial class MachineObject : global::ProtoBuf.IExtensible
//   {
//     public MachineObject() {}
//     
//     private proto.battleEditor.MapObjectType _type;
//     [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
//     public proto.battleEditor.MapObjectType Type
//     {
//       get { return _type; }
//       set { _type = value; }
//     }
//     private int _id;
//     [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
//     public int Id
//     {
//       get { return _id; }
//       set { _id = value; }
//     }
//     private int _lv;
//     [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"lv", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
//     public int Lv
//     {
//       get { return _lv; }
//       set { _lv = value; }
//     }
//     private global::ProtoBuf.IExtension extensionObject;
//     global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
//       { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
//   }
//   
//   [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GeneralObject")]
//   public partial class GeneralObject : global::ProtoBuf.IExtensible
//   {
//     public GeneralObject() {}
//     
//     private proto.battleEditor.MapObjectType _type;
//     [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
//     public proto.battleEditor.MapObjectType Type
//     {
//       get { return _type; }
//       set { _type = value; }
//     }
//     private int _id;
//     [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
//     public int Id
//     {
//       get { return _id; }
//       set { _id = value; }
//     }
//     private int _lv;
//     [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"lv", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
//     public int Lv
//     {
//       get { return _lv; }
//       set { _lv = value; }
//     }
//     private int _star;
//     [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"star", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
//     public int Star
//     {
//       get { return _star; }
//       set { _star = value; }
//     }
//     private global::ProtoBuf.IExtension extensionObject;
//     global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
//       { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
//   }
//   
//   [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapNode")]
//   public partial class MapNode : global::ProtoBuf.IExtensible
//   {
//     public MapNode() {}
//     
//     private int _rowIndex;
//     [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"rowIndex", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
//     public int RowIndex
//     {
//       get { return _rowIndex; }
//       set { _rowIndex = value; }
//     }
//     private int _columnIndex;
//     [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"columnIndex", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
//     public int ColumnIndex
//     {
//       get { return _columnIndex; }
//       set { _columnIndex = value; }
//     }
//     private bool _boundary;
//     [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"boundary", DataFormat = global::ProtoBuf.DataFormat.Default)]
//     public bool Boundary
//     {
//       get { return _boundary; }
//       set { _boundary = value; }
//     }
//     private bool _locked;
//     [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"locked", DataFormat = global::ProtoBuf.DataFormat.Default)]
//     public bool Locked
//     {
//       get { return _locked; }
//       set { _locked = value; }
//     }
//     private proto.battleEditor.MapObject _floor;
//     [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"floor", DataFormat = global::ProtoBuf.DataFormat.Default)]
//     public proto.battleEditor.MapObject Floor
//     {
//       get { return _floor; }
//       set { _floor = value; }
//     }
//     private proto.battleEditor.MapObject _foundation = null;
//     [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"foundation", DataFormat = global::ProtoBuf.DataFormat.Default)]
//     [global::System.ComponentModel.DefaultValue(null)]
//     public proto.battleEditor.MapObject Foundation
//     {
//       get { return _foundation; }
//       set { _foundation = value; }
//     }
//     private proto.battleEditor.MapObject _topography = null;
//     [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"topography", DataFormat = global::ProtoBuf.DataFormat.Default)]
//     [global::System.ComponentModel.DefaultValue(null)]
//     public proto.battleEditor.MapObject Topography
//     {
//       get { return _topography; }
//       set { _topography = value; }
//     }
//     private readonly global::System.Collections.Generic.List<proto.battleEditor.MapObject> _articles = new global::System.Collections.Generic.List<proto.battleEditor.MapObject>();
//     [global::ProtoBuf.ProtoMember(8, Name=@"articles", DataFormat = global::ProtoBuf.DataFormat.Default)]
//     public global::System.Collections.Generic.List<proto.battleEditor.MapObject> articles
//     {
//       get { return _articles; }
//     }
//   
//     private proto.battleEditor.GeneralObject _general = null;
//     [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"general", DataFormat = global::ProtoBuf.DataFormat.Default)]
//     [global::System.ComponentModel.DefaultValue(null)]
//     public proto.battleEditor.GeneralObject General
//     {
//       get { return _general; }
//       set { _general = value; }
//     }
//     private proto.battleEditor.MachineObject _machine = null;
//     [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"machine", DataFormat = global::ProtoBuf.DataFormat.Default)]
//     [global::System.ComponentModel.DefaultValue(null)]
//     public proto.battleEditor.MachineObject Machine
//     {
//       get { return _machine; }
//       set { _machine = value; }
//     }
//     private bool _roadblockEnable = default(bool);
//     [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"roadblockEnable", DataFormat = global::ProtoBuf.DataFormat.Default)]
//     [global::System.ComponentModel.DefaultValue(default(bool))]
//     public bool RoadblockEnable
//     {
//       get { return _roadblockEnable; }
//       set { _roadblockEnable = value; }
//     }
//     private global::ProtoBuf.IExtension extensionObject;
//     global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
//       { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
//   }
//   
//   [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapConfig")]
//   public partial class MapConfig : global::ProtoBuf.IExtensible
//   {
//     public MapConfig() {}
//     
//     private string _mapId;
//     [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mapId", DataFormat = global::ProtoBuf.DataFormat.Default)]
//     public string MapId
//     {
//       get { return _mapId; }
//       set { _mapId = value; }
//     }
//     private int _row;
//     [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"row", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
//     public int Row
//     {
//       get { return _row; }
//       set { _row = value; }
//     }
//     private int _column;
//     [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"column", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
//     public int Column
//     {
//       get { return _column; }
//       set { _column = value; }
//     }
//     private float _deltaX;
//     [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"deltaX", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
//     public float DeltaX
//     {
//       get { return _deltaX; }
//       set { _deltaX = value; }
//     }
//     private float _deltaY;
//     [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"deltaY", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
//     public float DeltaY
//     {
//       get { return _deltaY; }
//       set { _deltaY = value; }
//     }
//     private int _cellSize;
//     [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"cellSize", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
//     public int CellSize
//     {
//       get { return _cellSize; }
//       set { _cellSize = value; }
//     }
//     private string _background;
//     [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"background", DataFormat = global::ProtoBuf.DataFormat.Default)]
//     public string Background
//     {
//       get { return _background; }
//       set { _background = value; }
//     }
//     private readonly global::System.Collections.Generic.List<proto.battleEditor.MapNode> _nodes = new global::System.Collections.Generic.List<proto.battleEditor.MapNode>();
//     [global::ProtoBuf.ProtoMember(8, Name=@"nodes", DataFormat = global::ProtoBuf.DataFormat.Default)]
//     public global::System.Collections.Generic.List<proto.battleEditor.MapNode> Nodes
//     {
//       get { return _nodes; }
//     }
//   
//     private readonly global::System.Collections.Generic.List<int> _resourceId = new global::System.Collections.Generic.List<int>();
//     [global::ProtoBuf.ProtoMember(9, Name=@"resourceId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
//     public global::System.Collections.Generic.List<int> ResourceId
//     {
//       get { return _resourceId; }
//     }
//   
//     private global::ProtoBuf.IExtension extensionObject;
//     global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
//       { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
//   }
//   
//   [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EditorInfo")]
//   public partial class EditorInfo : global::ProtoBuf.IExtensible
//   {
//     public EditorInfo() {}
//     
//     private int _id = default(int);
//     [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
//     [global::System.ComponentModel.DefaultValue(default(int))]
//     public int Id
//     {
//       get { return _id; }
//       set { _id = value; }
//     }
//     private int _lv = default(int);
//     [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"lv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
//     [global::System.ComponentModel.DefaultValue(default(int))]
//     public int Lv
//     {
//       get { return _lv; }
//       set { _lv = value; }
//     }
//     private int _star = default(int);
//     [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"star", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
//     [global::System.ComponentModel.DefaultValue(default(int))]
//     public int Star
//     {
//       get { return _star; }
//       set { _star = value; }
//     }
//     private int _monsterId = default(int);
//     [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"monsterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
//     [global::System.ComponentModel.DefaultValue(default(int))]
//     public int MonsterId
//     {
//       get { return _monsterId; }
//       set { _monsterId = value; }
//     }
//     private int _step = default(int);
//     [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"step", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
//     [global::System.ComponentModel.DefaultValue(default(int))]
//     public int Step
//     {
//       get { return _step; }
//       set { _step = value; }
//     }
//     private Proto.Common.Int2 _inPoint = null;
//     [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"inPoint", DataFormat = global::ProtoBuf.DataFormat.Default)]
//     [global::System.ComponentModel.DefaultValue(null)]
//     public Proto.Common.Int2 InPoint
//     {
//       get { return _inPoint; }
//       set { _inPoint = value; }
//     }
//     private Proto.Common.Int2 _outPoint = null;
//     [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"outPoint", DataFormat = global::ProtoBuf.DataFormat.Default)]
//     [global::System.ComponentModel.DefaultValue(null)]
//     public Proto.Common.Int2 OutPoint
//     {
//       get { return _outPoint; }
//       set { _outPoint = value; }
//     }
//     private int _startTime = default(int);
//     [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"startTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
//     [global::System.ComponentModel.DefaultValue(default(int))]
//     public int StartTime
//     {
//       get { return _startTime; }
//       set { _startTime = value; }
//     }
//     private int _count = default(int);
//     [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
//     [global::System.ComponentModel.DefaultValue(default(int))]
//     public int Count
//     {
//       get { return _count; }
//       set { _count = value; }
//     }
//     private int _coin = default(int);
//     [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"coin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
//     [global::System.ComponentModel.DefaultValue(default(int))]
//     public int Coin
//     {
//       get { return _coin; }
//       set { _coin = value; }
//     }
//     private int _group = default(int);
//     [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"group", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
//     [global::System.ComponentModel.DefaultValue(default(int))]
//     public int Group
//     {
//       get { return _group; }
//       set { _group = value; }
//     }
//     
//     private int _teamId = default(int);
//     [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"teamId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
//     [global::System.ComponentModel.DefaultValue(default(int))]
//     public int TeamId
//     {
//       get { return _teamId; }
//       set { _teamId = value; }
//     }
//     private global::ProtoBuf.IExtension extensionObject;
//     global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
//       { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
//   }
//   
//   [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MonsterInfo")]
//   public partial class MonsterInfo : global::ProtoBuf.IExtensible
//   {
//     public MonsterInfo() {}
//     
//     private int _monsterId;
//     [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"monsterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
//     public int MonsterId
//     {
//       get { return _monsterId; }
//       set { _monsterId = value; }
//     }
//     private int _lv;
//     [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"lv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
//     public int Lv
//     {
//       get { return _lv; }
//       set { _lv = value; }
//     }
//     private int _star;
//     [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"star", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
//     public int Star
//     {
//       get { return _star; }
//       set { _star = value; }
//     }
//     private readonly global::System.Collections.Generic.List<proto.common.Reward> _reward = new global::System.Collections.Generic.List<proto.common.Reward>();
//     [global::ProtoBuf.ProtoMember(4, Name=@"reward", DataFormat = global::ProtoBuf.DataFormat.Default)]
//     public global::System.Collections.Generic.List<proto.common.Reward> reward
//     {
//       get { return _reward; }
//     }
//   
//     private Proto.Common.Int2 _inPoint;
//     [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"inPoint", DataFormat = global::ProtoBuf.DataFormat.Default)]
//     public Proto.Common.Int2 InPoint
//     {
//       get { return _inPoint; }
//       set { _inPoint = value; }
//     }
//     private int _group;
//     [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"group", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
//     public int Group
//     {
//       get { return _group; }
//       set { _group = value; }
//     }
//     private int _time;
//     [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
//     public int Time
//     {
//       get { return _time; }
//       set { _time = value; }
//     }
//     private global::ProtoBuf.IExtension extensionObject;
//     global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
//       { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
//   }
//   
//   [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoundInfo")]
//   public partial class RoundInfo : global::ProtoBuf.IExtensible
//   {
//     public RoundInfo() {}
//     
//     private int _id;
//     [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
//     public int Id
//     {
//       get { return _id; }
//       set { _id = value; }
//     }
//     private readonly global::System.Collections.Generic.List<proto.battleEditor.MonsterInfo> _monsters = new global::System.Collections.Generic.List<proto.battleEditor.MonsterInfo>();
//     [global::ProtoBuf.ProtoMember(2, Name=@"monsters", DataFormat = global::ProtoBuf.DataFormat.Default)]
//     public global::System.Collections.Generic.List<proto.battleEditor.MonsterInfo> monsters
//     {
//       get { return _monsters; }
//     }
//   
//     private int _roundTime;
//     [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"roundTime", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
//     public int RoundTime
//     {
//       get { return _roundTime; }
//       set { _roundTime = value; }
//     }
//     private readonly global::System.Collections.Generic.List<proto.common.Reward> _finishReward = new global::System.Collections.Generic.List<proto.common.Reward>();
//     [global::ProtoBuf.ProtoMember(4, Name=@"finishReward", DataFormat = global::ProtoBuf.DataFormat.Default)]
//     public global::System.Collections.Generic.List<proto.common.Reward> finishReward
//     {
//       get { return _finishReward; }
//     }
//   
//     private readonly global::System.Collections.Generic.List<proto.common.Reward> _leftTimeReward = new global::System.Collections.Generic.List<proto.common.Reward>();
//     [global::ProtoBuf.ProtoMember(5, Name=@"leftTimeReward", DataFormat = global::ProtoBuf.DataFormat.Default)]
//     public global::System.Collections.Generic.List<proto.common.Reward> leftTimeReward
//     {
//       get { return _leftTimeReward; }
//     }
//   
//     private int _modulus;
//     [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"modulus", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
//     public int Modulus
//     {
//       get { return _modulus; }
//       set { _modulus = value; }
//     }
//     private int _duration;
//     [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"duration", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
//     public int Duration
//     {
//       get { return _duration; }
//       set { _duration = value; }
//     }
//     private readonly global::System.Collections.Generic.List<proto.battleEditor.OutPointGroup> _groups = new global::System.Collections.Generic.List<proto.battleEditor.OutPointGroup>();
//     [global::ProtoBuf.ProtoMember(8, Name=@"groups", DataFormat = global::ProtoBuf.DataFormat.Default)]
//     public global::System.Collections.Generic.List<proto.battleEditor.OutPointGroup> Groups
//     {
//       get { return _groups; }
//     }
//   
//     private readonly global::System.Collections.Generic.List<proto.battleEditor.EditorInfo> _infos = new global::System.Collections.Generic.List<proto.battleEditor.EditorInfo>();
//     [global::ProtoBuf.ProtoMember(9, Name=@"infos", DataFormat = global::ProtoBuf.DataFormat.Default)]
//     public global::System.Collections.Generic.List<proto.battleEditor.EditorInfo> Infos
//     {
//       get { return _infos; }
//     }
//   
//     private global::ProtoBuf.IExtension extensionObject;
//     global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
//       { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
//   }
//   
//   [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoundConfig")]
//   public partial class RoundConfig : global::ProtoBuf.IExtensible
//   {
//     public RoundConfig() {}
//     
//     private readonly global::System.Collections.Generic.List<proto.battleEditor.RoundInfo> _rounds = new global::System.Collections.Generic.List<proto.battleEditor.RoundInfo>();
//     [global::ProtoBuf.ProtoMember(1, Name=@"rounds", DataFormat = global::ProtoBuf.DataFormat.Default)]
//     public global::System.Collections.Generic.List<proto.battleEditor.RoundInfo> Rounds
//     {
//       get { return _rounds; }
//     }
//   
//     private global::ProtoBuf.IExtension extensionObject;
//     global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
//       { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
//   }
//   
//   [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OutPointGroup")]
//   public partial class OutPointGroup : global::ProtoBuf.IExtensible
//   {
//     public OutPointGroup() {}
//     
//     private int _id;
//     [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
//     public int Id
//     {
//       get { return _id; }
//       set { _id = value; }
//     }
//     private readonly global::System.Collections.Generic.List<Proto.Common.Int2> _outPoints = new global::System.Collections.Generic.List<Proto.Common.Int2>();
//     [global::ProtoBuf.ProtoMember(2, Name=@"outPoints", DataFormat = global::ProtoBuf.DataFormat.Default)]
//     public global::System.Collections.Generic.List<Proto.Common.Int2> OutPoints
//     {
//       get { return _outPoints; }
//     }
//   
//     private readonly global::System.Collections.Generic.List<Proto.Common.Int2> _inPoints = new global::System.Collections.Generic.List<Proto.Common.Int2>();
//     [global::ProtoBuf.ProtoMember(3, Name=@"inPoints", DataFormat = global::ProtoBuf.DataFormat.Default)]
//     public global::System.Collections.Generic.List<Proto.Common.Int2> InPoints
//     {
//       get { return _inPoints; }
//     }
//   
//     private global::ProtoBuf.IExtension extensionObject;
//     
//     private int _teamId;
//     [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"teamId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
//     public int TeamId
//     {
//       get { return _teamId; }
//       set { _teamId = value; }
//     }
//
//     global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
//       { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
//   }
//   
//     [global::ProtoBuf.ProtoContract(Name=@"MapObjectType")]
//     public enum MapObjectType
//     {
//             
//       [global::ProtoBuf.ProtoEnum(Name=@"Floor", Value=0)]
//       Floor = 0,
//             
//       [global::ProtoBuf.ProtoEnum(Name=@"Topography", Value=1)]
//       Topography = 1,
//             
//       [global::ProtoBuf.ProtoEnum(Name=@"Foundation", Value=2)]
//       Foundation = 2,
//             
//       [global::ProtoBuf.ProtoEnum(Name=@"Article", Value=3)]
//       Article = 3,
//             
//       [global::ProtoBuf.ProtoEnum(Name=@"General", Value=4)]
//       General = 4,
//             
//       [global::ProtoBuf.ProtoEnum(Name=@"Machine", Value=5)]
//       Machine = 5
//     }
//   
// }