// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/cmd.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Proto.Cmd {

  /// <summary>Holder for reflection information generated from proto/cmd.proto</summary>
  public static partial class CmdReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/cmd.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CmdReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9wcm90by9jbWQucHJvdG8SCXByb3RvLmNtZCrEAgoHUHVzaENtZBIOCglF",
            "cnJvckNvZGUQiScSCwoGS2lja2VkEJgnEg0KCExFVkVMX1VQEJonEg8KClRh",
            "c2tVcGRhdGUQ4icSEAoLSVRFTV9VUERBVEUQnCcSEgoNUm9sbGluZ05vdGlj",
            "ZRCyKBIVChBST0xFX05BTUVfQ0hBTkdFELMoEhsKFlJPTEVfUkFOS19MQUJF",
            "TF9DSEFOR0UQtCgSEwoOUk9MRV9HVUlERV9BREQQtSgSFgoRUk9MRV9HRU5F",
            "UkFMU19BREQQtigSGAoTUk9MRV9TS0lMTF9DQVJEX0FERBC3KBIYChNST0xF",
            "X0dFTkVSQUxfQ0hBTkdFELgoEhsKFlJPTEVfQ0FSRF9HUk9VUF9DSEFOR0UQ",
            "uSgSEQoMU0VSVkVSX0lORk9TENAoEhEKDFZJRVdfUkVXQVJEUxDaKCq5CwoH",
            "RWNob0NtZBIPCgpQTEFZRVJfTUlOEPAuEgoKBUhlYXJ0EPEuEhEKDFJlbG9h",
            "ZENvbmZpZxDyLhINCghSb2xlSW5mbxDzLhINCghCdXlQb3dlchD0LhIMCgdC",
            "dXlHb2xkEPUuEhEKDENIQU5HRV9HVUlERRD2LhINCghVcFBpbkppZRD3LhIc",
            "ChdST0xFX0NPTU1PTl9JTkZPX0NIQU5HRRD4LhIOCglDZGtSZXdhcmQQ+S4S",
            "FwoSQ2hhbmdlUGVyc29uYWxEYXRhEPsuEhIKDVN0YXRpc3RpY3NMb2cQ/S4S",
            "DQoIVXBkYXRlTWUQ/i4SFQoQQ0FSRF9HUk9VUF9JTkZPUxCELxIaChVBRERf",
            "VVBEQVRFX0NBUkRfR1JPVVAQhS8SBwoCR00Qji8SFQoQRmlnaHRWYWxSYW5r",
            "TGlzdBCPLxIMCgdEaW5nSGFvEJAvEhUKEE1lc3NhZ2VQaWRVcGRhdGUQkS8S",
            "HAoXR21DaGFuZ2VUZWNobm9sb2d5TGV2ZWwQki8SIgodR21CYW5kaXRzQW5k",
            "UmViZWxsaW91c09wZXJhdGUQky8SGwoWU0lNUExFX0NIQVBURVJfTUlTU0lP",
            "ThCYLxIZChRDSEFQVEVSX01JU1NJT05fTElTVBCZLxIUCg9MRVZFTF9VUF9O",
            "T1RJQ0UQmi8SDQoIU3RvcmVCdXkQwC8SDgoJU3RvcmVMaXN0EMEvEhEKDFN0",
            "b3JlUmVmcmVzaBDCLxITCg5Db21tb25TdG9yZUJ1eRDDLxIYChNTaG93UmVj",
            "ZWl2ZUl0ZW1MaXN0EMQvEhQKD0RpYW1vbmRTdG9yZUJ1eRDFLxIVChBEaWFt",
            "b25kU3RvcmVJbmZvEMYvEg4KCU1BSUxfTElTVBDCMBIRCgxNQUlMX09QRVJB",
            "VEUQwzASEQoMUmFjZUxhbXBMaXN0ENgxEhMKDkFkZE5ld1JhY2VMYW1wENkx",
            "Eg8KCk5vdGljZUxpc3QQ4jESDQoIU2lnbkluZm8Q7DESCwoGRG9TaWduEO0x",
            "EhEKDFJlY2hhcmdlSW5mbxCUMhIQCgtyZWNoYXJnZVN1YxCVMhIJCgRSQU5L",
            "EKgyEhcKElJBTktfVEFQX1JPTEVfSU5GTxCpMhIYChNSQU5LX1NFVF9ST0xF",
            "X0xBQkVMEKoyEhMKDkdFTkVSQUxfQUNUSVZFEOQyEhQKD0dFTkVSQUxfVVBf",
            "U1RBUhDlMhIRCgxBQ0hJRVZFX0xJU1QQ7zISIQocQ0FURUdPUllfQUNISUVW",
            "RV9SRVdBUkRfVEFLRRDwMhIYChNBQ0hJRVZFX1JFV0FSRF9UQUtFEPEyEg8K",
            "ClBMQVlFUl9NQVgQwD4SEQoMUExBVEZPUk1fTUlOEME+EgoKBUxvZ2luEMI+",
            "Eg8KCkNyZWF0ZVJvbGUQwz4SEwoOR21TZW5kQ3VycmVuY3kQxD4SDwoKR21T",
            "ZW5kSXRlbRDFPhIMCgdCYW5Vc2VyEMY+EhAKC05ld1JhY2VMYW1wEMo+EhAK",
            "C0RlbFJhY2VMYW1wEMs+EhsKFkNoYW5nZVJhY2VMYW1wSW50ZXJ2YWwQzD4S",
            "DgoJTmV3Tm90aWNlEM0+Eg4KCURlbE5vdGljZRDOPhIVChBQbGF0Zm9ybVJl",
            "Y2hhcmdlEM8+Eg0KCEJhblNodUdtENA+EhIKDUdtR2V0Um9sZUxpc3QQ0T4S",
            "FQoQR21VcGRhdGVSb2xlSW5mbxDSPhIOCglHbUdlbmVyYWwQ0z4SDgoJR21T",
            "b2xkaWVyENQ+EhQKD0dtVXBkYXRlR2VuZXJhbBDVPhIUCg9HbVVwZGF0ZVNv",
            "bGRpZXIQ1j4SEQoMR21TdHJhdGVnaWNzENc+EhcKEkdtVXBkYXRlU3RyYXRl",
            "Z2ljcxDYPhIYChNERUxFVEVfVVNFUl9BQ0NPVU5UEJlDEg4KCUxPR0lOX09V",
            "VBCaQxIRCgxQTEFURk9STV9NQVgQkE4qWwoOSW5uZXJTZXJ2ZXJDbWQSDwoK",
            "Uk9MRV9MT0dJThCRThIOCglST0xFX0VYSVQQk04SEAoLS0lDS19QTEFZRVIQ",
            "lk4SFgoRUHVzaFJvbGxpbmdOb3RpY2UQl05CIgoZY29tLnNnLnByb3RvYnVm",
            "LnByb3RvLmNtZEIDQ21kUAA="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Proto.Cmd.PushCmd), typeof(global::Proto.Cmd.EchoCmd), typeof(global::Proto.Cmd.InnerServerCmd), }, null, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// 整个协议号范围[5000, 10000]
  /// </summary>
  public enum PushCmd {
    [pbr::OriginalName("ErrorCode")] ErrorCode = 5001,
    /// <summary>
    /// 当前玩家被踢了
    /// </summary>
    [pbr::OriginalName("Kicked")] Kicked = 5016,
    /// <summary>
    /// 玩家的等级提升了
    /// </summary>
    [pbr::OriginalName("LEVEL_UP")] LevelUp = 5018,
    /// <summary>
    /// 任务
    /// </summary>
    [pbr::OriginalName("TaskUpdate")] TaskUpdate = 5090,
    /// <summary>
    /// 道具
    /// </summary>
    [pbr::OriginalName("ITEM_UPDATE")] ItemUpdate = 5020,
    /// <summary>
    /// 推送一个滚动公告
    /// </summary>
    [pbr::OriginalName("RollingNotice")] RollingNotice = 5170,
    /// <summary>
    /// 玩家修改名字
    /// </summary>
    [pbr::OriginalName("ROLE_NAME_CHANGE")] RoleNameChange = 5171,
    /// <summary>
    /// 排行榜中的个人标签修改
    /// </summary>
    [pbr::OriginalName("ROLE_RANK_LABEL_CHANGE")] RoleRankLabelChange = 5172,
    /// <summary>
    /// 玩家引导新增
    /// </summary>
    [pbr::OriginalName("ROLE_GUIDE_ADD")] RoleGuideAdd = 5173,
    /// <summary>
    /// 玩家武将新增
    /// </summary>
    [pbr::OriginalName("ROLE_GENERALS_ADD")] RoleGeneralsAdd = 5174,
    /// <summary>
    /// 玩家武将新增
    /// </summary>
    [pbr::OriginalName("ROLE_SKILL_CARD_ADD")] RoleSkillCardAdd = 5175,
    /// <summary>
    /// 玩家武将的等级、星级修改
    /// </summary>
    [pbr::OriginalName("ROLE_GENERAL_CHANGE")] RoleGeneralChange = 5176,
    /// <summary>
    /// 玩家卡组修改
    /// </summary>
    [pbr::OriginalName("ROLE_CARD_GROUP_CHANGE")] RoleCardGroupChange = 5177,
    /// <summary>
    /// 服务端的gate、fight信息
    /// </summary>
    [pbr::OriginalName("SERVER_INFOS")] ServerInfos = 5200,
    /// <summary>
    /// 服务端推送奖励，专门用于展示。
    /// </summary>
    [pbr::OriginalName("VIEW_REWARDS")] ViewRewards = 5210,
  }

  public enum EchoCmd {
    /// <summary>
    ////////////////////////////////网关 ==>> 玩家服///////////////////////////////////////////////
    /// </summary>
    [pbr::OriginalName("PLAYER_MIN")] PlayerMin = 6000,
    /// <summary>
    /// 心跳
    /// </summary>
    [pbr::OriginalName("Heart")] Heart = 6001,
    /// <summary>
    /// 请求重新加载配置文件
    /// </summary>
    [pbr::OriginalName("ReloadConfig")] ReloadConfig = 6002,
    /// <summary>
    /// 角色信息
    /// </summary>
    [pbr::OriginalName("RoleInfo")] RoleInfo = 6003,
    /// <summary>
    /// 购买体力
    /// </summary>
    [pbr::OriginalName("BuyPower")] BuyPower = 6004,
    /// <summary>
    /// 购买金币（每日）
    /// </summary>
    [pbr::OriginalName("BuyGold")] BuyGold = 6005,
    /// <summary>
    /// 更新引导
    /// </summary>
    [pbr::OriginalName("CHANGE_GUIDE")] ChangeGuide = 6006,
    /// <summary>
    /// 升级品阶
    /// </summary>
    [pbr::OriginalName("UpPinJie")] UpPinJie = 6007,
    /// <summary>
    /// 换头像、换头像框、改名
    /// </summary>
    [pbr::OriginalName("ROLE_COMMON_INFO_CHANGE")] RoleCommonInfoChange = 6008,
    /// <summary>
    /// 礼包码
    /// </summary>
    [pbr::OriginalName("CdkReward")] CdkReward = 6009,
    /// <summary>
    /// 修改自定义数据
    /// </summary>
    [pbr::OriginalName("ChangePersonalData")] ChangePersonalData = 6011,
    /// <summary>
    /// 统计日志 | 客户端日志打点
    /// </summary>
    [pbr::OriginalName("StatisticsLog")] StatisticsLog = 6013,
    /// <summary>
    /// 客户端请求更新他的信息 （随机据点 ）
    /// </summary>
    [pbr::OriginalName("UpdateMe")] UpdateMe = 6014,
    /// <summary>
    /// 卡组信息
    /// </summary>
    [pbr::OriginalName("CARD_GROUP_INFOS")] CardGroupInfos = 6020,
    /// <summary>
    /// 新增、修改卡组
    /// </summary>
    [pbr::OriginalName("ADD_UPDATE_CARD_GROUP")] AddUpdateCardGroup = 6021,
    /// <summary>
    /// 客户端使用的   gm命令
    /// </summary>
    [pbr::OriginalName("GM")] Gm = 6030,
    /// <summary>
    /// 战力排行
    /// </summary>
    [pbr::OriginalName("FightValRankList")] FightValRankList = 6031,
    /// <summary>
    /// 顶号通知
    /// </summary>
    [pbr::OriginalName("DingHao")] DingHao = 6032,
    [pbr::OriginalName("MessagePidUpdate")] MessagePidUpdate = 6033,
    /// <summary>
    /// gm 发送玩家服
    /// </summary>
    [pbr::OriginalName("GmChangeTechnologyLevel")] GmChangeTechnologyLevel = 6034,
    /// <summary>
    /// 反叛和盗匪操作
    /// </summary>
    [pbr::OriginalName("GmBanditsAndRebelliousOperate")] GmBanditsAndRebelliousOperate = 6035,
    /// <summary>
    /// 简单的章节关卡信息
    /// </summary>
    [pbr::OriginalName("SIMPLE_CHAPTER_MISSION")] SimpleChapterMission = 6040,
    /// <summary>
    /// 章节关卡列表
    /// </summary>
    [pbr::OriginalName("CHAPTER_MISSION_LIST")] ChapterMissionList = 6041,
    /// <summary>
    /// 等级提升通知
    /// </summary>
    [pbr::OriginalName("LEVEL_UP_NOTICE")] LevelUpNotice = 6042,
    /// <summary>
    /// 商店
    /// </summary>
    [pbr::OriginalName("StoreBuy")] StoreBuy = 6080,
    /// <summary>
    /// 商店列表
    /// </summary>
    [pbr::OriginalName("StoreList")] StoreList = 6081,
    /// <summary>
    /// 刷新商店
    /// </summary>
    [pbr::OriginalName("StoreRefresh")] StoreRefresh = 6082,
    /// <summary>
    /// 普通商店购买
    /// </summary>
    [pbr::OriginalName("CommonStoreBuy")] CommonStoreBuy = 6083,
    /// <summary>
    /// 客户端弹出面板显示获得到的道具
    /// </summary>
    [pbr::OriginalName("ShowReceiveItemList")] ShowReceiveItemList = 6084,
    /// <summary>
    /// 元宝商店购买
    /// </summary>
    [pbr::OriginalName("DiamondStoreBuy")] DiamondStoreBuy = 6085,
    /// <summary>
    /// 元宝商店信息
    /// </summary>
    [pbr::OriginalName("DiamondStoreInfo")] DiamondStoreInfo = 6086,
    /// <summary>
    /// 邮箱
    /// </summary>
    [pbr::OriginalName("MAIL_LIST")] MailList = 6210,
    /// <summary>
    /// 邮件操作
    /// </summary>
    [pbr::OriginalName("MAIL_OPERATE")] MailOperate = 6211,
    /// <summary>
    /// 跑马灯
    /// </summary>
    [pbr::OriginalName("RaceLampList")] RaceLampList = 6360,
    /// <summary>
    /// 新跑马灯
    /// </summary>
    [pbr::OriginalName("AddNewRaceLamp")] AddNewRaceLamp = 6361,
    /// <summary>
    /// 公告
    /// </summary>
    [pbr::OriginalName("NoticeList")] NoticeList = 6370,
    /// <summary>
    /// 签到
    /// </summary>
    [pbr::OriginalName("SignInfo")] SignInfo = 6380,
    /// <summary>
    /// 签到
    /// </summary>
    [pbr::OriginalName("DoSign")] DoSign = 6381,
    /// <summary>
    /// 充值
    /// </summary>
    [pbr::OriginalName("RechargeInfo")] RechargeInfo = 6420,
    /// <summary>
    /// 充值成功
    /// </summary>
    [pbr::OriginalName("rechargeSuc")] RechargeSuc = 6421,
    /// <summary>
    /// 排行榜
    /// </summary>
    [pbr::OriginalName("RANK")] Rank = 6440,
    /// <summary>
    /// 排行榜点击时的个人展示框
    /// </summary>
    [pbr::OriginalName("RANK_TAP_ROLE_INFO")] RankTapRoleInfo = 6441,
    /// <summary>
    /// 排行榜设置自己的标签
    /// </summary>
    [pbr::OriginalName("RANK_SET_ROLE_LABEL")] RankSetRoleLabel = 6442,
    /// <summary>
    /// 武将的激活
    /// </summary>
    [pbr::OriginalName("GENERAL_ACTIVE")] GeneralActive = 6500,
    /// <summary>
    /// 武将的升星
    /// </summary>
    [pbr::OriginalName("GENERAL_UP_STAR")] GeneralUpStar = 6501,
    /// <summary>
    /// 成就列表
    /// </summary>
    [pbr::OriginalName("ACHIEVE_LIST")] AchieveList = 6511,
    /// <summary>
    /// 领取类别成就奖励
    /// </summary>
    [pbr::OriginalName("CATEGORY_ACHIEVE_REWARD_TAKE")] CategoryAchieveRewardTake = 6512,
    /// <summary>
    /// 领取小成就奖励
    /// </summary>
    [pbr::OriginalName("ACHIEVE_REWARD_TAKE")] AchieveRewardTake = 6513,
    /// <summary>
    ////////////////////////////////网关 ==>> 玩家服///////////////////////////////////////////////
    /// </summary>
    [pbr::OriginalName("PLAYER_MAX")] PlayerMax = 8000,
    /// <summary>
    ////////////////////////////////网关 ==>> 平台服///////////////////////////////////////////////
    /// </summary>
    [pbr::OriginalName("PLATFORM_MIN")] PlatformMin = 8001,
    /// <summary>
    /// 登陆
    /// </summary>
    [pbr::OriginalName("Login")] Login = 8002,
    /// <summary>
    /// 创角
    /// </summary>
    [pbr::OriginalName("CreateRole")] CreateRole = 8003,
    /// <summary>
    /// 后台送货币000
    /// </summary>
    [pbr::OriginalName("GmSendCurrency")] GmSendCurrency = 8004,
    /// <summary>
    /// 后台送道具
    /// </summary>
    [pbr::OriginalName("GmSendItem")] GmSendItem = 8005,
    /// <summary>
    /// 封号
    /// </summary>
    [pbr::OriginalName("BanUser")] BanUser = 8006,
    /// <summary>
    /// 新跑马灯
    /// </summary>
    [pbr::OriginalName("NewRaceLamp")] NewRaceLamp = 8010,
    /// <summary>
    /// 删除跑马灯
    /// </summary>
    [pbr::OriginalName("DelRaceLamp")] DelRaceLamp = 8011,
    /// <summary>
    /// 更改跑马灯间隔时间
    /// </summary>
    [pbr::OriginalName("ChangeRaceLampInterval")] ChangeRaceLampInterval = 8012,
    /// <summary>
    /// 新公告
    /// </summary>
    [pbr::OriginalName("NewNotice")] NewNotice = 8013,
    /// <summary>
    /// 删除公告
    /// </summary>
    [pbr::OriginalName("DelNotice")] DelNotice = 8014,
    /// <summary>
    /// 充值
    /// </summary>
    [pbr::OriginalName("PlatformRecharge")] PlatformRecharge = 8015,
    [pbr::OriginalName("BanShuGm")] BanShuGm = 8016,
    /// <summary>
    /// role集合
    /// </summary>
    [pbr::OriginalName("GmGetRoleList")] GmGetRoleList = 8017,
    /// <summary>
    /// GM修改玩家数据
    /// </summary>
    [pbr::OriginalName("GmUpdateRoleInfo")] GmUpdateRoleInfo = 8018,
    /// <summary>
    /// GM修改玩家数据
    /// </summary>
    [pbr::OriginalName("GmGeneral")] GmGeneral = 8019,
    /// <summary>
    /// GM修改玩家数据
    /// </summary>
    [pbr::OriginalName("GmSoldier")] GmSoldier = 8020,
    /// <summary>
    /// GM修改玩家数据
    /// </summary>
    [pbr::OriginalName("GmUpdateGeneral")] GmUpdateGeneral = 8021,
    /// <summary>
    /// GM修改玩家数据
    /// </summary>
    [pbr::OriginalName("GmUpdateSoldier")] GmUpdateSoldier = 8022,
    /// <summary>
    /// GM修改玩家数据
    /// </summary>
    [pbr::OriginalName("GmStrategics")] GmStrategics = 8023,
    /// <summary>
    /// GM修改玩家数据
    /// </summary>
    [pbr::OriginalName("GmUpdateStrategics")] GmUpdateStrategics = 8024,
    /// <summary>
    /// 删除账号请求
    /// </summary>
    [pbr::OriginalName("DELETE_USER_ACCOUNT")] DeleteUserAccount = 8601,
    /// <summary>
    /// 退出账号
    /// </summary>
    [pbr::OriginalName("LOGIN_OUT")] LoginOut = 8602,
    /// <summary>
    ////////////////////////////////网关 ==>> 平台服///////////////////////////////////////////////
    /// </summary>
    [pbr::OriginalName("PLATFORM_MAX")] PlatformMax = 10000,
  }

  /// <summary>
  /// 内部服务器 通信 使用的协议  10001 ~  11000
  /// </summary>
  public enum InnerServerCmd {
    /// <summary>
    /// 网关 &lt;=> 其他服，  有玩家成功登陆， 需要绑定roleId-Gate 关系
    /// </summary>
    [pbr::OriginalName("ROLE_LOGIN")] RoleLogin = 10001,
    /// <summary>
    /// 网关 &lt;=> 其他服，  有玩家 退出了， 需要解绑 roleId-Gate 关系
    /// </summary>
    [pbr::OriginalName("ROLE_EXIT")] RoleExit = 10003,
    /// <summary>
    /// 其他服 => 网关，  通知网关把某个玩家给踢掉 string: roleId,int: reason. [0=BAN,1=顶号]
    /// </summary>
    [pbr::OriginalName("KICK_PLAYER")] KickPlayer = 10006,
    /// <summary>
    /// 其他服 => 网关，  有一个新公告
    /// </summary>
    [pbr::OriginalName("PushRollingNotice")] PushRollingNotice = 10007,
  }

  #endregion

}

#endregion Designer generated code
