//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: function.proto
namespace proto.function
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FunctionStatus")]
  public partial class FunctionStatus : global::ProtoBuf.IExtensible
  {
    public FunctionStatus() {}
    
    private int _functionId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"functionId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int functionId
    {
      get { return _functionId; }
      set { _functionId = value; }
    }
    private bool _redPoint;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"redPoint", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool redPoint
    {
      get { return _redPoint; }
      set { _redPoint = value; }
    }
    private bool _lock;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"lock", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool @lock
    {
      get { return _lock; }
      set { _lock = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PushFunctionStatus")]
  public partial class PushFunctionStatus : global::ProtoBuf.IExtensible
  {
    public PushFunctionStatus() {}
    
    private int _functionId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"functionId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int functionId
    {
      get { return _functionId; }
      set { _functionId = value; }
    }
    private bool _redPoint;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"redPoint", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool redPoint
    {
      get { return _redPoint; }
      set { _redPoint = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqFunctionList")]
  public partial class ReqFunctionList : global::ProtoBuf.IExtensible
  {
    public ReqFunctionList() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResFunctionList")]
  public partial class ResFunctionList : global::ProtoBuf.IExtensible
  {
    public ResFunctionList() {}
    
    private readonly global::System.Collections.Generic.List<proto.function.FunctionStatus> _list = new global::System.Collections.Generic.List<proto.function.FunctionStatus>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<proto.function.FunctionStatus> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqChangeFunctionStatus")]
  public partial class ReqChangeFunctionStatus : global::ProtoBuf.IExtensible
  {
    public ReqChangeFunctionStatus() {}
    
    private int _functionId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"functionId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int functionId
    {
      get { return _functionId; }
      set { _functionId = value; }
    }
    private bool _redPoint;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"redPoint", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool redPoint
    {
      get { return _redPoint; }
      set { _redPoint = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResChangeFunctionStatus")]
  public partial class ResChangeFunctionStatus : global::ProtoBuf.IExtensible
  {
    public ResChangeFunctionStatus() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}