//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: gm.proto
namespace proto.gm
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqGmLogin")]
  public partial class ReqGmLogin : global::ProtoBuf.IExtensible
  {
    public ReqGmLogin() {}
    
    private long _time;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long time
    {
      get { return _time; }
      set { _time = value; }
    }
    private string _signStr;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"signStr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string signStr
    {
      get { return _signStr; }
      set { _signStr = value; }
    }
    private string _loginStr;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"loginStr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string loginStr
    {
      get { return _loginStr; }
      set { _loginStr = value; }
    }
    private string _username;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string username
    {
      get { return _username; }
      set { _username = value; }
    }
    private int _gateTmpId = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"gateTmpId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gateTmpId
    {
      get { return _gateTmpId; }
      set { _gateTmpId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResGmLogin")]
  public partial class ResGmLogin : global::ProtoBuf.IExtensible
  {
    public ResGmLogin() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private string _roleId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roleId
    {
      get { return _roleId; }
      set { _roleId = value; }
    }
    private int _gateTmpId = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"gateTmpId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gateTmpId
    {
      get { return _gateTmpId; }
      set { _gateTmpId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}