//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: innerServer.proto
namespace proto.innerserver
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginFromGate")]
  public partial class LoginFromGate : global::ProtoBuf.IExtensible
  {
    public LoginFromGate() {}
    
    private int _tempId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"tempId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tempId
    {
      get { return _tempId; }
      set { _tempId = value; }
    }
    private bool _success = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"success", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool success
    {
      get { return _success; }
      set { _success = value; }
    }
    private string _roleId = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string roleId
    {
      get { return _roleId; }
      set { _roleId = value; }
    }
    private byte[] _data;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] data
    {
      get { return _data; }
      set { _data = value; }
    }
    private string _loginIp = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"loginIp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string loginIp
    {
      get { return _loginIp; }
      set { _loginIp = value; }
    }
    private int _gateServerId = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"gateServerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gateServerId
    {
      get { return _gateServerId; }
      set { _gateServerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqHandShakeMessage")]
  public partial class ReqHandShakeMessage : global::ProtoBuf.IExtensible
  {
    public ReqHandShakeMessage() {}
    
    private string _key;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string key
    {
      get { return _key; }
      set { _key = value; }
    }
    private int _gateServerId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"gateServerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int gateServerId
    {
      get { return _gateServerId; }
      set { _gateServerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResHandShakeMessage")]
  public partial class ResHandShakeMessage : global::ProtoBuf.IExtensible
  {
    public ResHandShakeMessage() {}
    
    private int _serverType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"serverType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int serverType
    {
      get { return _serverType; }
      set { _serverType = value; }
    }
    private int _serverId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"serverId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int serverId
    {
      get { return _serverId; }
      set { _serverId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"InnerServerCommonMessage")]
  public partial class InnerServerCommonMessage : global::ProtoBuf.IExtensible
  {
    public InnerServerCommonMessage() {}
    
    private string _paramString = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"paramString", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string paramString
    {
      get { return _paramString; }
      set { _paramString = value; }
    }
    private int _paramInt = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"paramInt", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int paramInt
    {
      get { return _paramInt; }
      set { _paramInt = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqRefreshOnlinePlayerCache")]
  public partial class ReqRefreshOnlinePlayerCache : global::ProtoBuf.IExtensible
  {
    public ReqRefreshOnlinePlayerCache() {}
    
    private readonly global::System.Collections.Generic.List<string> _roleList = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(1, Name=@"roleList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> roleList
    {
      get { return _roleList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqRefreshConfigList")]
  public partial class ReqRefreshConfigList : global::ProtoBuf.IExtensible
  {
    public ReqRefreshConfigList() {}
    
    private readonly global::System.Collections.Generic.List<string> _fileList = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(1, Name=@"fileList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> fileList
    {
      get { return _fileList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}