//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: login.proto
namespace proto.login
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqLoginAccount")]
  public partial class ReqLoginAccount : global::ProtoBuf.IExtensible
  {
    public ReqLoginAccount() {}
    
    private proto.login.LoginType _loginType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"loginType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public proto.login.LoginType loginType
    {
      get { return _loginType; }
      set { _loginType = value; }
    }
    private string _loginStr;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"loginStr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string loginStr
    {
      get { return _loginStr; }
      set { _loginStr = value; }
    }
    private string _channel;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"channel", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string channel
    {
      get { return _channel; }
      set { _channel = value; }
    }
    private proto.login.DevicePlatformType _devicePlatform;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"devicePlatform", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public proto.login.DevicePlatformType devicePlatform
    {
      get { return _devicePlatform; }
      set { _devicePlatform = value; }
    }
    private int _loginServerId;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"loginServerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int loginServerId
    {
      get { return _loginServerId; }
      set { _loginServerId = value; }
    }
    private string _extra = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"extra", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string extra
    {
      get { return _extra; }
      set { _extra = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResLoginAccount")]
  public partial class ResLoginAccount : global::ProtoBuf.IExtensible
  {
    public ResLoginAccount() {}
    
    private bool _hasRole;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"hasRole", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool hasRole
    {
      get { return _hasRole; }
      set { _hasRole = value; }
    }
    private int _realNameAuth;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"realNameAuth", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int realNameAuth
    {
      get { return _realNameAuth; }
      set { _realNameAuth = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqCreateRole")]
  public partial class ReqCreateRole : global::ProtoBuf.IExtensible
  {
    public ReqCreateRole() {}
    
    private string _nickname;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nickname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string nickname
    {
      get { return _nickname; }
      set { _nickname = value; }
    }
    private string _face;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"face", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string face
    {
      get { return _face; }
      set { _face = value; }
    }
    private int _sex;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResCreateRole")]
  public partial class ResCreateRole : global::ProtoBuf.IExtensible
  {
    public ResCreateRole() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"LoginType")]
    public enum LoginType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Account", Value=1)]
      Account = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DeviceId", Value=2)]
      DeviceId = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Phone", Value=3)]
      Phone = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"DevicePlatformType")]
    public enum DevicePlatformType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Unknown", Value=1)]
      Unknown = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"IOS", Value=2)]
      IOS = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Android", Value=3)]
      Android = 3
    }
  
}