//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: mail.proto
// Note: requires additional types generated from: common.proto
namespace proto.mail
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MailInfoMsg")]
  public partial class MailInfoMsg : global::ProtoBuf.IExtensible
  {
    public MailInfoMsg() {}
    
    private string _mailId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mailId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string mailId
    {
      get { return _mailId; }
      set { _mailId = value; }
    }
    private int _mailType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"mailType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mailType
    {
      get { return _mailType; }
      set { _mailType = value; }
    }
    private string _title;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"title", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string title
    {
      get { return _title; }
      set { _title = value; }
    }
    private string _detail;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"detail", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string detail
    {
      get { return _detail; }
      set { _detail = value; }
    }
    private string _attachment;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"attachment", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string attachment
    {
      get { return _attachment; }
      set { _attachment = value; }
    }
    private string _sender;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"sender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sender
    {
      get { return _sender; }
      set { _sender = value; }
    }
    private string _senderNickname;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"senderNickname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string senderNickname
    {
      get { return _senderNickname; }
      set { _senderNickname = value; }
    }
    private proto.mail.MailStatus _mailStatus;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"mailStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public proto.mail.MailStatus mailStatus
    {
      get { return _mailStatus; }
      set { _mailStatus = value; }
    }
    private long _sendTime;
    [global::ProtoBuf.ProtoMember(20, IsRequired = true, Name=@"sendTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long sendTime
    {
      get { return _sendTime; }
      set { _sendTime = value; }
    }
    private long _overdueTime;
    [global::ProtoBuf.ProtoMember(21, IsRequired = true, Name=@"overdueTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long overdueTime
    {
      get { return _overdueTime; }
      set { _overdueTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqGetMailList")]
  public partial class ReqGetMailList : global::ProtoBuf.IExtensible
  {
    public ReqGetMailList() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResGetMailList")]
  public partial class ResGetMailList : global::ProtoBuf.IExtensible
  {
    public ResGetMailList() {}
    
    private readonly global::System.Collections.Generic.List<proto.mail.MailInfoMsg> _mailList = new global::System.Collections.Generic.List<proto.mail.MailInfoMsg>();
    [global::ProtoBuf.ProtoMember(1, Name=@"mailList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<proto.mail.MailInfoMsg> mailList
    {
      get { return _mailList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqOperateMail")]
  public partial class ReqOperateMail : global::ProtoBuf.IExtensible
  {
    public ReqOperateMail() {}
    
    private int _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _mailIdList = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(2, Name=@"mailIdList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> mailIdList
    {
      get { return _mailIdList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResOperateMail")]
  public partial class ResOperateMail : global::ProtoBuf.IExtensible
  {
    public ResOperateMail() {}
    
    private int _successMailCount;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"successMailCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int successMailCount
    {
      get { return _successMailCount; }
      set { _successMailCount = value; }
    }
    private readonly global::System.Collections.Generic.List<proto.common.IntPairMsg> _rewards = new global::System.Collections.Generic.List<proto.common.IntPairMsg>();
    [global::ProtoBuf.ProtoMember(2, Name=@"rewards", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<proto.common.IntPairMsg> rewards
    {
      get { return _rewards; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PushNewMail")]
  public partial class PushNewMail : global::ProtoBuf.IExtensible
  {
    public PushNewMail() {}
    
    private proto.mail.MailInfoMsg _mailInfo;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mailInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public proto.mail.MailInfoMsg mailInfo
    {
      get { return _mailInfo; }
      set { _mailInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PushOverdueMailAttachments")]
  public partial class PushOverdueMailAttachments : global::ProtoBuf.IExtensible
  {
    public PushOverdueMailAttachments() {}
    
    private readonly global::System.Collections.Generic.List<proto.mail.MailInfoMsg> _list = new global::System.Collections.Generic.List<proto.mail.MailInfoMsg>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<proto.mail.MailInfoMsg> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"MailStatus")]
    public enum MailStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Unread", Value=1)]
      Unread = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Read", Value=2)]
      Read = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReceiveAttachment", Value=3)]
      ReceiveAttachment = 3
    }
  
}