//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: role.proto
// Note: requires additional types generated from: common.proto
namespace proto.role
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerInfoMsg")]
  public partial class PlayerInfoMsg : global::ProtoBuf.IExtensible
  {
    public PlayerInfoMsg() {}
    
    private string _roleId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roleId
    {
      get { return _roleId; }
      set { _roleId = value; }
    }
    private string _roleName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roleName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roleName
    {
      get { return _roleName; }
      set { _roleName = value; }
    }
    private long _exp;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private int _level;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private long _diamond;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"diamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long diamond
    {
      get { return _diamond; }
      set { _diamond = value; }
    }
    private long _gold;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long gold
    {
      get { return _gold; }
      set { _gold = value; }
    }
    private int _power;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"power", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int power
    {
      get { return _power; }
      set { _power = value; }
    }
    private string _face;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"face", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string face
    {
      get { return _face; }
      set { _face = value; }
    }
    private int _sex;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private long _createTime;
    [global::ProtoBuf.ProtoMember(100, IsRequired = true, Name=@"createTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long createTime
    {
      get { return _createTime; }
      set { _createTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerBriefInfoMsg")]
  public partial class PlayerBriefInfoMsg : global::ProtoBuf.IExtensible
  {
    public PlayerBriefInfoMsg() {}
    
    private string _roleId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roleId
    {
      get { return _roleId; }
      set { _roleId = value; }
    }
    private string _roleName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roleName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roleName
    {
      get { return _roleName; }
      set { _roleName = value; }
    }
    private int _level;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private string _headFrame;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"headFrame", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string headFrame
    {
      get { return _headFrame; }
      set { _headFrame = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ItemGridInfoMsg")]
  public partial class ItemGridInfoMsg : global::ProtoBuf.IExtensible
  {
    public ItemGridInfoMsg() {}
    
    private int _bagIndex;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"bagIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bagIndex
    {
      get { return _bagIndex; }
      set { _bagIndex = value; }
    }
    private int _count;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int count
    {
      get { return _count; }
      set { _count = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ItemInfoMsg")]
  public partial class ItemInfoMsg : global::ProtoBuf.IExtensible
  {
    public ItemInfoMsg() {}
    
    private int _itemId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"itemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int itemId
    {
      get { return _itemId; }
      set { _itemId = value; }
    }
    private int _count;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int count
    {
      get { return _count; }
      set { _count = value; }
    }
    private readonly global::System.Collections.Generic.List<proto.role.ItemGridInfoMsg> _grids = new global::System.Collections.Generic.List<proto.role.ItemGridInfoMsg>();
    [global::ProtoBuf.ProtoMember(3, Name=@"grids", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<proto.role.ItemGridInfoMsg> grids
    {
      get { return _grids; }
    }
  
    private long _expiredTime;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"expiredTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long expiredTime
    {
      get { return _expiredTime; }
      set { _expiredTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PushPlayerWasKicked")]
  public partial class PushPlayerWasKicked : global::ProtoBuf.IExtensible
  {
    public PushPlayerWasKicked() {}
    
    private int _reason;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"reason", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int reason
    {
      get { return _reason; }
      set { _reason = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqMyPlayerInfo")]
  public partial class ReqMyPlayerInfo : global::ProtoBuf.IExtensible
  {
    public ReqMyPlayerInfo() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResMyPlayerInfo")]
  public partial class ResMyPlayerInfo : global::ProtoBuf.IExtensible
  {
    public ResMyPlayerInfo() {}
    
    private proto.role.PlayerInfoMsg _playerInfo;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public proto.role.PlayerInfoMsg playerInfo
    {
      get { return _playerInfo; }
      set { _playerInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqChangeHeadFrame")]
  public partial class ReqChangeHeadFrame : global::ProtoBuf.IExtensible
  {
    public ReqChangeHeadFrame() {}
    
    private int _headFrame;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"headFrame", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int headFrame
    {
      get { return _headFrame; }
      set { _headFrame = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResChangeHeadFrame")]
  public partial class ResChangeHeadFrame : global::ProtoBuf.IExtensible
  {
    public ResChangeHeadFrame() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqStatisticsLog")]
  public partial class ReqStatisticsLog : global::ProtoBuf.IExtensible
  {
    public ReqStatisticsLog() {}
    
    private int _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _jsonParameters;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"jsonParameters", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string jsonParameters
    {
      get { return _jsonParameters; }
      set { _jsonParameters = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResStatisticsLog")]
  public partial class ResStatisticsLog : global::ProtoBuf.IExtensible
  {
    public ResStatisticsLog() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqPlayerBriefInfo")]
  public partial class ReqPlayerBriefInfo : global::ProtoBuf.IExtensible
  {
    public ReqPlayerBriefInfo() {}
    
    private string _roleId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roleId
    {
      get { return _roleId; }
      set { _roleId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResPlayerBriefInfo")]
  public partial class ResPlayerBriefInfo : global::ProtoBuf.IExtensible
  {
    public ResPlayerBriefInfo() {}
    
    private proto.role.PlayerBriefInfoMsg _briefInfo;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"briefInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public proto.role.PlayerBriefInfoMsg briefInfo
    {
      get { return _briefInfo; }
      set { _briefInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqMyItemList")]
  public partial class ReqMyItemList : global::ProtoBuf.IExtensible
  {
    public ReqMyItemList() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResMyItemList")]
  public partial class ResMyItemList : global::ProtoBuf.IExtensible
  {
    public ResMyItemList() {}
    
    private readonly global::System.Collections.Generic.List<proto.role.ItemInfoMsg> _list = new global::System.Collections.Generic.List<proto.role.ItemInfoMsg>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<proto.role.ItemInfoMsg> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PushPlayerItemInfoChange")]
  public partial class PushPlayerItemInfoChange : global::ProtoBuf.IExtensible
  {
    public PushPlayerItemInfoChange() {}
    
    private readonly global::System.Collections.Generic.List<proto.role.ItemInfoMsg> _itemInfo = new global::System.Collections.Generic.List<proto.role.ItemInfoMsg>();
    [global::ProtoBuf.ProtoMember(1, Name=@"itemInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<proto.role.ItemInfoMsg> itemInfo
    {
      get { return _itemInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}