//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: UserData.proto
namespace proto.core
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Currency")]
  public partial class Currency : global::ProtoBuf.IExtensible
  {
    public Currency() {}
    
    private int _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private long _count;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long count
    {
      get { return _count; }
      set { _count = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MissionInfo")]
  public partial class MissionInfo : global::ProtoBuf.IExtensible
  {
    public MissionInfo() {}
    
    private string _missionId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"missionId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string missionId
    {
      get { return _missionId; }
      set { _missionId = value; }
    }
    private string _lastMissionId = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"lastMissionId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string lastMissionId
    {
      get { return _lastMissionId; }
      set { _lastMissionId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MissionStarInfo")]
  public partial class MissionStarInfo : global::ProtoBuf.IExtensible
  {
    public MissionStarInfo() {}
    
    private string _missionId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"missionId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string missionId
    {
      get { return _missionId; }
      set { _missionId = value; }
    }
    private int _starCount;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"starCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int starCount
    {
      get { return _starCount; }
      set { _starCount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GoodsInfo")]
  public partial class GoodsInfo : global::ProtoBuf.IExtensible
  {
    public GoodsInfo() {}
    
    private int _goodsId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"goodsId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int goodsId
    {
      get { return _goodsId; }
      set { _goodsId = value; }
    }
    private int _remainCount;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"remainCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int remainCount
    {
      get { return _remainCount; }
      set { _remainCount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CardInfo")]
  public partial class CardInfo : global::ProtoBuf.IExtensible
  {
    public CardInfo() {}
    
    private int _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _Id = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private long _time = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long time
    {
      get { return _time; }
      set { _time = value; }
    }
    private int _count = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int count
    {
      get { return _count; }
      set { _count = value; }
    }
    private int _isNew = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"isNew", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int isNew
    {
      get { return _isNew; }
      set { _isNew = value; }
    }
    private int _lv = (int)1;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"lv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)1)]
    public int lv
    {
      get { return _lv; }
      set { _lv = value; }
    }
    private int _star = (int)1;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"star", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)1)]
    public int star
    {
      get { return _star; }
      set { _star = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"User")]
  public partial class User : global::ProtoBuf.IExtensible
  {
    public User() {}
    
    private readonly global::System.Collections.Generic.List<proto.core.Currency> _currency = new global::System.Collections.Generic.List<proto.core.Currency>();
    [global::ProtoBuf.ProtoMember(1, Name=@"currency", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<proto.core.Currency> currency
    {
      get { return _currency; }
    }
  
    private string _account;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string account
    {
      get { return _account; }
      set { _account = value; }
    }
    private proto.core.MissionInfo _missionInfo;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"missionInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public proto.core.MissionInfo missionInfo
    {
      get { return _missionInfo; }
      set { _missionInfo = value; }
    }
    private int _goldCount;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"goldCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int goldCount
    {
      get { return _goldCount; }
      set { _goldCount = value; }
    }
    private int _hp;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private int _exploit = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"exploit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int exploit
    {
      get { return _exploit; }
      set { _exploit = value; }
    }
    private readonly global::System.Collections.Generic.List<proto.core.CardInfo> _cards = new global::System.Collections.Generic.List<proto.core.CardInfo>();
    [global::ProtoBuf.ProtoMember(7, Name=@"cards", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<proto.core.CardInfo> cards
    {
      get { return _cards; }
    }
  
    private readonly global::System.Collections.Generic.List<proto.core.GoodsInfo> _goodsInfo = new global::System.Collections.Generic.List<proto.core.GoodsInfo>();
    [global::ProtoBuf.ProtoMember(8, Name=@"goodsInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<proto.core.GoodsInfo> goodsInfo
    {
      get { return _goodsInfo; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _itemIds = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(9, Name=@"itemIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> itemIds
    {
      get { return _itemIds; }
    }
  
    private readonly global::System.Collections.Generic.List<proto.core.CardInfo> _lineUpIds = new global::System.Collections.Generic.List<proto.core.CardInfo>();
    [global::ProtoBuf.ProtoMember(10, Name=@"lineUpIds", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<proto.core.CardInfo> lineUpIds
    {
      get { return _lineUpIds; }
    }
  
    private readonly global::System.Collections.Generic.List<proto.core.TipType> _tipType = new global::System.Collections.Generic.List<proto.core.TipType>();
    [global::ProtoBuf.ProtoMember(11, Name=@"tipType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<proto.core.TipType> tipType
    {
      get { return _tipType; }
    }
  
    private readonly global::System.Collections.Generic.List<proto.core.MissionStarInfo> _missionStarInfo = new global::System.Collections.Generic.List<proto.core.MissionStarInfo>();
    [global::ProtoBuf.ProtoMember(13, Name=@"missionStarInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<proto.core.MissionStarInfo> missionStarInfo
    {
      get { return _missionStarInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"TipType")]
    public enum TipType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"General", Value=1)]
      General = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Machine", Value=2)]
      Machine = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Store", Value=3)]
      Store = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Chapter", Value=4)]
      Chapter = 4
    }
  
}